#!/usr/bin/env sh

find . -name "traduora-config.json" -type f -delete
if [ "$(uname)" == "Darwin" ]; then
  sed -i '.bak' '/^    traduoraProjectId/d' build.gradle

  find . -name "*.bak" -type f -delete
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
  sed -i '/^    traduoraProjectId/d' build.gradle
fi


cd app || exit
if [ "$(uname)" == "Darwin" ]; then
  sed -i '.bak' 's/\import groovy.json.JsonSlurper//g' build.gradle
  sed -i '.bak' '\:// START signingConfigs BLOCK:,\:// END signingConfigs BLOCK:d' build.gradle
  sed -i '.bak' '\:// START TRADUORA BLOCK:,\:// END TRADUORA BLOCK:d' build.gradle

  find . -name "*.bak" -type f -delete
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
  sed -i 's/\import groovy.json.JsonSlurper//g' build.gradle
  sed -i '\:// START signingConfigs BLOCK:,\:// END signingConfigs BLOCK:d' build.gradle
  sed -i '\:// START TRADUORA BLOCK:,\:// END TRADUORA BLOCK:d' build.gradle
fi

find . -name "*.jks" -type f -delete
